### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by MoMMde**
# What?
I did some small changes to the Project
e.g. Typo fix or chaning type of Kind

### CODE REVIEW

**Comment by DRSchlaubi** [comment]
You need to .1 bump the version of uno and game animator, otherwise the update system won't update it

**Comment by MoMMde** [comment]
> You need to .1 bump the version of uno and game animator, otherwise the update system won't update it

noted and done

**Comment by DRSchlaubi** [comment]
Uhm

**Comment by MoMMde** [comment]
so I fixed it and it now passes the CI test :)

**Pull request merged**
